version: '3.8'
services:
  mysql:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - my_db_volume:/var/lib/mysql
volumes:
  my_db_volume:
